### ISSUE TITLE
New Feature Request: Command Line Support

### ISSUE THREAD

**Issue by nhudacin** [ErikEJ/SqlQueryStress#10]
Requesting that the SqlQueryStress tool allow for command line interactions. I would like to be able to test any incoming changes in a CI environment, record the results, and then determine if that change meets minimum performance criteria. 

I think this would be a really great feature to draw more people to this project and I can think of several uses along the lines of performance monitoring/tracking. 

I think these would need to be exposed to the command line interface: 
- Query/SQL File
- Connection information
- Number of iterations/Threads

What I would want back... 
An general overview of the run (Elapsed Time, Client Seconds/Iteration, CPU Seconds/Iteration, Actual Seconds/Iteration, # of Exceptions, Logical Reads/Iteration)

**Comment by denisreznik** [comment]
This is nice suggestion, I love to have cmd integration too. But you wrote: "What I would want back... 
 An general overview of the run (Elapsed Time, Client Seconds/Iteration, CPU Seconds/Iteration, Actual Seconds/Iteration, # of Exceptions, Logical Reads/Iteration)", is this really necessary? I mean that this is not necessary, typically you are just generate load with the tool and then gather execution statistics using Profiler, EE and other tools.

**Comment by denisreznik** [comment]
One more suggestion if you don't mind :) There is a nice cmd tool for running queries in parallel - ostress, which is a part of RML Tools package. A lot of people including myself are using it. It is very simple and have an intuitive cmd interface. This tool is nice but was not updated for more than a year. It will be good if cmd for SqlQueryStress will use the same command and extends ostress features: random parameters substitution, etc. This will allow SqlQueryStress to be used by current ostress users easily and will add intuitive cmd interface for SqlQueryStress.

**Comment by nhudacin** [comment]
Keep the suggestions coming! 

I want statistics back from SQL Stress because I'll be testing stored procedures under different amounts of load. We do a lot of transactions and I think I can use this tool to recreate stale indexes, statistics, etc --> getting this information back will help me green-light a stored procedure release. If the SP is 20% or more slower under the same amount of load than previous to your update, no way!

I'm going to check out os stress now! Thanks!

**Comment by maialithar** [comment]
Is this enhancment still needed? Or maybe ostress is enough? :)

**Comment by ErikEJ** [comment]
Let us close it for now
