### ISSUE TITLE
Elapsed Time doesn't line up with Actual seconds/iteration

### ISSUE THREAD

**Issue by jedthe3rd** [ErikEJ/SqlQueryStress#104]
I am seeing some inconsistency with the Elapsed Time. 

I have a query that I am comparing an old vs a new version. I was expecting the new version to be significantly faster.
SQLQueryStress wasn't showing that when comparing the Elapsed Time. 

I dug into it further and I was able to use extended events to verify the AVG execution time for the query is significantly faster (2.5-3.5x). This is shown in the Actual Seconds/Iteration (Avg) but is not reflected in the Elapsed Time. The Elapsed Time shows about the same to slightly slower when compared with the old.

My settings are as follows:

The code is run inside a transaction.
![image](https://user-images.githubusercontent.com/7817335/98027335-c2470b80-1dc9-11eb-9b08-a774657c288c.png)

In every respect the new version should have faster elapsed time.
I can't share the query exactly but the skeleton is this:
OLD
```
begin tran
DECLARE @var BINARY(8);
EXEC dbo.stored_procedure_old @var = @var OUTPUT
rollback tran
```
NEW
```
begin tran
DECLARE @var BINARY(8);
EXEC dbo.stored_procedure_old @var = @var OUTPUT
rollback tran
```

I think the main point here is that the NEW stored procedure runs significantly fast but that isn't reflected in the elapsed time.

If you have an idea of what part of the SQLQueryStress code is causing the problem I can look at the code in context of my stored procedure and see if I can't identify anything specific since I can't share the stored procedure code.

----
Edit:

Some more context -
The new stored procedure basically was made to be parallel run where the old stored procedure was completely serial. The old stored procedure had to wait for any other instance of it to finish before it could run. The new one is parallel up to a partitioned amount.

**Comment by ErikEJ** [comment]
Look at the code that calculates the Elapsed time ???

**Comment by mdnMachine** [comment]
I recommend profiling reads/writes, CPU time, memory, blocks/deadlocks and comparing query plans for the stored procedures. It's possible the new procedure is faster when run alone but has more blocking or other issues when running in parallel. It's not necessarily SQLQueryStress that's at issue. I'd want to rule those things out first.

**Comment by jedthe3rd** [comment]
> I recommend profiling reads/writes, CPU time, memory, blocks/deadlocks and comparing query plans for the stored procedures. It's possible the new procedure is faster when run alone but has more blocking or other issues when running in parallel. It's not necessarily SQLQueryStress that's at issue. I'd want to rule those things out first.

I am doing some more testing to rule those out.

**Comment by jedthe3rd** [comment]
Looks like it's not the stored procedures:
I ran the stored procedures 40400 times each and collected the data using xevents.
Waits xevent: 
```SQL
CREATE EVENT SESSION [SA_query_monitor] ON SERVER 
ADD EVENT sqlserver.sql_batch_completed(SET collect_batch_text=(1)
    ACTION(package0.event_sequence,sqlserver.client_app_name,sqlserver.client_pid,sqlserver.database_id,sqlserver.nt_username,sqlserver.query_hash,sqlserver.server_principal_name,sqlserver.session_id,sqlserver.sql_text)
    WHERE ([package0].[equal_boolean]([sqlserver].[is_system],(0)) AND [sqlserver].[like_i_sql_unicode_string]([sqlserver].[client_app_name],N'SQLQueryStress') AND [sqlserver].[like_i_sql_unicode_string]([batch_text],N'begin tran%rollback TRAN')))
ADD TARGET package0.ring_buffer(SET max_events_limit=(1000000))
WITH (MAX_MEMORY=8192 KB,EVENT_RETENTION_MODE=ALLOW_SINGLE_EVENT_LOSS,MAX_DISPATCH_LATENCY=5 SECONDS,MAX_EVENT_SIZE=0 KB,MEMORY_PARTITION_MODE=PER_CPU,TRACK_CAUSALITY=ON,STARTUP_STATE=OFF)
GO

```
Waits duration (milliseconds) and amount:
New stored proc -
![image](https://user-images.githubusercontent.com/7817335/98179815-eb949400-1ebc-11eb-8ad4-a5a743751701.png)
Old stored proc -
![image](https://user-images.githubusercontent.com/7817335/98179837-fb13dd00-1ebc-11eb-99fd-0edd7ff4776a.png)

Average run time and logical reads:
XEvent:
```SQL
CREATE EVENT SESSION [SA wait_info] ON SERVER 
ADD EVENT sqlos.wait_info(
    ACTION(package0.collect_cpu_cycle_time,package0.collect_current_thread_id,package0.collect_system_time,package0.event_sequence,sqlos.cpu_id,sqlos.numa_node_id,sqlos.scheduler_address,sqlos.scheduler_id,sqlos.system_thread_id,sqlos.task_time,sqlserver.client_app_name,sqlserver.client_connection_id,sqlserver.client_pid,sqlserver.compile_plan_guid,sqlserver.context_info,sqlserver.database_id,sqlserver.database_name,sqlserver.session_id,sqlserver.session_resource_group_id,sqlserver.session_resource_pool_id,sqlserver.sql_text,sqlserver.transaction_id,sqlserver.username)
    WHERE ([sqlserver].[equal_i_sql_unicode_string]([sqlserver].[database_name],N'a') AND [sqlserver].[equal_i_sql_unicode_string]([sqlserver].[client_app_name],N'SQLQueryStress')))
ADD TARGET package0.ring_buffer(SET max_events_limit=(10000))
WITH (MAX_MEMORY=4096 KB,EVENT_RETENTION_MODE=ALLOW_SINGLE_EVENT_LOSS,MAX_DISPATCH_LATENCY=30 SECONDS,MAX_EVENT_SIZE=0 KB,MEMORY_PARTITION_MODE=NONE,TRACK_CAUSALITY=OFF,STARTUP_STATE=OFF)
GO

```
Top is new (14 row_count) Bottom is old (17 row_count) - Duration (Microseconds)
![image](https://user-images.githubusercontent.com/7817335/98179896-1252ca80-1ebd-11eb-8b12-83ffae3efba0.png)

**Comment by jedthe3rd** [comment]
I added an edit to explain the difference between the two procedures if that makes a difference.

**Comment by mdnMachine** [comment]
I'm not sure what the 'Top is new (14 row_count) Bottom is old (17 row_count) - Duration (Microseconds)' data is showing or if the stored procedures were ran 40400 times each in parallel or serially. The code to generate times looks right to me. My best guess is that when using 200 threads, the CPU of the client is burdened and it's affecting the 'client seconds' reading. The CPU and Actual seconds are what SQL is reporting and they show the stored procedure has improved.

**Comment by jedthe3rd** [comment]
> I'm not sure what the 'Top is new (14 row_count) Bottom is old (17 row_count) - Duration (Microseconds)' data is showing or if the stored procedures were ran 40400 times each in parallel or serially. The code to generate times looks right to me. My best guess is that when using 200 threads, the CPU of the client is burdened and it's affecting the 'client seconds' reading. The CPU and Actual seconds are what SQL is reporting and they show the stored procedure has improved.

The old stored procedure and the new one were run 40400 times. The old stored proc locks the table the stored procedure runs against so each thread (of the 200) has to wait for the previous one to run (serial). The new stored proc implements row level locks instead which allows multiple instances of the stores proc to run at a time (parallel). The first row (top) is the new stored procedure, and the second row (bottom) is the old stored procedure.

If it's client overhead then testing on a more powerful system (more everything, cpu, ram, network bandwidth) should improve things, right? Do you think the threading management could be improved?

**Comment by ErikEJ** [comment]
Maybe related to this?https://github.com/ErikEJ/SqlQueryStress/pull/110

**Comment by mdnMachine** [comment]
Erik's guess is a good one. The SQL stats showing in SQLQueryStress seems to show an order of magnitude improvement, but the client time is still the same. That could easily be the minimum time to run the garbage collector you're seeing. Can you try again now that the garbage collection call has been removed?

**Comment by jedthe3rd** [comment]
Ya this definitely sounds like it might have been the issue. I will test sometime next week.

**Comment by ErikEJ** [comment]
@jedthe3rd Any test results?
