### ISSUE TITLE
Download marked as "Virus detected"

### ISSUE THREAD

**Issue by DevlinSchoonraad** [ErikEJ/SqlQueryStress#105]
When downloading the release I receive "Virus detected" message from Chrome in windows.

![image](https://user-images.githubusercontent.com/1246669/99935322-1ca01000-2d69-11eb-9111-20aa8591894d.png)

**Comment by ErikEJ** [comment]
Have you tried installing the version published in the Microsoft store?

**Comment by DevlinSchoonraad** [comment]
I have been unable to install Store Apps, some issue with MS Store not installing on my machine. Will disable virus scanner and use the zip.

**Comment by ErikEJ** [comment]
I will update the version in the Store.

**Comment by ErikEJ** [comment]
Store version updated
