### ISSUE TITLE
AppVeyor link is down

### ISSUE THREAD

**Issue by BrentOzar** [ErikEJ/SqlQueryStress#112]
On the repo home page, the link to the AppVeyor file here:
https://ci.appveyor.com/api/projects/ErikEJ/SqlQueryStress/artifacts/SqlQueryStress.zip?branch=master

Produces an error:
{"message":"Artifact not found or access denied."}

**Comment by ErikEJ** [comment]
AppVeyor artifacts now only last 1 month.

I need to find a better place to host the artifact.

I have manually kicked a new build in the meantime.

**Comment by ErikEJ** [comment]
Will investigate publish to Azure blob
