### ISSUE TITLE
Connect to Azure SQL Server databases?

### ISSUE THREAD

**Issue by open-environment** [ErikEJ/SqlQueryStress#113]
Attempting to connect to a remote Azure SQL Server instance, and getting connection failed. Can it be confirmed whether this use case is supported?

**Comment by ErikEJ** [comment]
Yes, latest version supports most Azure authentication methods

**Comment by ErikEJ** [comment]
Ping? Can you share your connection string?

**Comment by francesco1119** [comment]
Hi @ErikEJ , what is missing is the **Azure Active Directory - Universal with MFA**. 

![image](https://user-images.githubusercontent.com/3397477/189125018-701a08a1-0964-4b5f-9e62-9bbbc2bb4ac1.png)

Thank you

**Comment by ErikEJ** [comment]
Ah!

**Comment by ErikEJ** [comment]
Fixed in latest daily

**Comment by totodeluss** [comment]
I am using the above mentioned [SqlQueryStressNet6.zip](https://github.com/ErikEJ/SqlQueryStress/releases/download/102/SqlQueryStressNet6.zip) from the Sep 13, 2022 but I don't see an option for Azure Active Directory - Universal with MFA in the Authentication drop down (similarly to the screenshot from francesco1119). Not sure if am missing something here

**Comment by ErikEJ** [comment]
@totodeluss Looks like it was never properly implemented - working on a fix

**Comment by ErikEJ** [comment]
@open-environment @totodeluss @francesco1119 Updated latest release with actual Azure MFA support (user must be admin on logical server)
