### ISSUE TITLE
Exception when clicking the URL in AboutBox

### ISSUE THREAD

**Issue by koen-debacker** [ErikEJ/SqlQueryStress#116]
When clicking the URL in AboutBox I get an Exception:
![image](https://user-images.githubusercontent.com/6150967/148966231-6b157d8c-98eb-4190-8395-493f9a7184ae.png)

I'm fairly certain it's because of some changes in .NET Core:
https://stackoverflow.com/questions/59716856/net-core-3-1-process-startwww-website-com-not-working-in-wpf/59716904

**Comment by ErikEJ** [comment]
PR ?

**Comment by ErikEJ** [comment]
Thanks!
