### ISSUE TITLE
localhost as default server name 

### ISSUE THREAD

**Issue by fredatgithub** [ErikEJ/SqlQueryStress#120]
When I start the application, it would be great if localhost would be the default server name.
Would you accept a PR for that ?

**Comment by ErikEJ** [comment]
I am not sure - what is the default.

Maybe it should be (local) ?

**Comment by fredatgithub** [comment]
the default is string.Empty

**Comment by ErikEJ** [comment]
I think it should be (local), not localhost

**Comment by fredatgithub** [comment]
if you ping local, it doesn't work whereas ping localhost works

**Comment by ErikEJ** [comment]
Possibly but that is not a usual name of a SQL Server instance

**Comment by fredatgithub** [comment]
localhost is not an SQL instance but the name of the local pc
If I use the default SQL instance then its name is not necessary

**Comment by ErikEJ** [comment]
What's the point of making this change then?

**Comment by fredatgithub** [comment]
the point is to have a default value and not type it every time

**Comment by ErikEJ** [comment]
Yes, I understand, and "(local)" is a good default value.

**Comment by fredatgithub** [comment]
"local" may looks cool but it doesn't work on a Windows machine.

**Comment by fredatgithub** [comment]
you're right, I didn't know.
so do you prefer (local) instead of localhost?

**Comment by ErikEJ** [comment]
Yes please, as [suggested 5 days ago](https://github.com/ErikEJ/SqlQueryStress/issues/120#issuecomment-1011899901)

**Comment by fredatgithub** [comment]
ok
