### ISSUE TITLE
Launch a 'New Window' from GUI Application

### ISSUE THREAD

**Issue by joeiannone** [ErikEJ/SqlQueryStress#131]
I want to propose a new feature that allows you to launch and run multiple concurrent GUI windows. 

This would involve creating a class to manage the multiple application threads which would subscribe to a new action event in FormMain triggered by an added `New Window` drop down item in the menu strip. When this event is received, a new application thread would be created and started.

I have experimented with this and it seems doable. Does this seem like something that would be a good addition?

**Comment by ErikEJ** [comment]
Not sure it is something I feel like supporting. 

You can just launch the tool multiple times...

**Comment by joeiannone** [comment]
@ErikEJ that is a good point. I definitely overthought this. My proposal could be extremely simplified in that case. 

The feature request in that case would be to add the ability to launch a "new window" from the GUI app. Would involve adding a `New Window` item to the menu strip drop down. The respective on click method with then simply launch a new process.

**Comment by ErikEJ** [comment]
To be the Devils advocate: how about command line parameters from the parent launcher?
