### ISSUE TITLE
[Request] Add stand alone download for sqlstresscmd

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [ErikEJ/SqlQueryStress#139]
sqlstresscmd is a very useful tool in many cases. But it has to be installed from the Internet. Some of my servers don't have an Internet connection, so it's not possible to install sqlstresscmd. Is it possible to provide an offline install option? Thanks!

**Comment by ErikEJ** [comment]
Download the package from nuget and unzip?

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
Oh, thank you! I didn't know that is possible.

**Comment by ErikEJ** [comment]
I will Update to docs.
