### ISSUE TITLE
Multiple Iterations/Threads causes "Connection was open" Exceptions

### ISSUE THREAD

**Issue by pitchreport** [ErikEJ/SqlQueryStress#14]
I see that conn.Close(); was removed from LoadEngine.cs. That causes exceptions due to open connections.

This can be fixed by adding conn.Close(); at ln445 of LoadEngine.cs (I think). I'd prefer for smarter minds than mine to verify and implement the fix.

**Comment by ErikEJ** [comment]
Fixed in the latest source, pls let me know if that fixes your issue

**Comment by pitchreport** [comment]
That took care of it. Thanks, Erik.
