### ISSUE TITLE
Can't use SQLQueryStress on servers with wildcard certificates

### ISSUE THREAD

**Issue by djshelto** [ErikEJ/SqlQueryStress#141]
Because of the way my company does things, 2 of the servers I want to test have wildcard certs (*.<domain>.com) instead of proper certs.  This causes SQS to refuse to connect, throwing the following error into the System error log:

> The certificate received from the remote server does not contain the expected name. It is therefore not possible to determine whether we are connecting to the correct server. The server name we were expecting is <server>.<FQDN>. The TLS connection request has failed. The attached data contains the server certificate.

Is there, or is it possible to add, a work around for this?
Thanks!
-dennis

**Comment by 124me** [comment]
Whitecloud

**Comment by ErikEJ** [comment]
@124me  ???

**Comment by ErikEJ** [comment]
@124me Can you connect to the database using Microsoft.Data.SqlClient from a console app, and if so, what does your connection string look like?

**Comment by djshelto** [comment]
According to this, SQLClient is on v5.0.1...should I try with that?

**Comment by ErikEJ** [comment]
@djshelto  I prefer you try with 3.1.1 as that is the version used by the tool

**Comment by djshelto** [comment]
Ok, I figured out how to get that version.  Here're the results.
![2023-01-19 - SQLClient - user-pass security](https://user-images.githubusercontent.com/91497514/213470272-fc714fc2-e647-4ccf-b8e7-4f05164270d1.png)
![2023-01-19 - SQLClient - Integrated security](https://user-images.githubusercontent.com/91497514/213470276-31635e62-cbc3-44ba-86ac-5aa948c01343.png)

**Comment by djshelto** [comment]
Yeah, I'm mostly a SQL/SSIS developer :)

adding that to the connection string got it working.

**Comment by djshelto** [comment]
Thanks, I was able to tweak the source code to connect to the 2 servers in question!

Have a great one!
-dennis
