### ISSUE TITLE
The cmd version prints help text twice

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [ErikEJ/SqlQueryStress#144]
I modified the cmd version's target framework like this:
```
<TargetFrameworks>netcoreapp3.1;net6.0;net6.0-windows</TargetFrameworks>
```
Then I build them with:
```
dotnet publish -c Release --self-contained true -r win-x64 -p:PublishSingleFile=true -p:IncludeAllContentForSelfExtract=true -o ./publish --framework net6.0-windows
```
After that, I have two executables. However, when I run `sqlstresscmd.exe --help`, I got this:

```
C:\repo\SqlQueryStress\src\publish>sqlstresscmd.exe --help
sqlstresscmd 0.9.14.0
Copyright ©  2006, 2007 Adam Machanic

  -s, --settingsFile    File name of saved session settings

  -d, --dbserver        Database Server

  -t, --threads         Number of threads, default 1

  -i, --input           Path to .sql script to execute

  -x, --xtract          Extract sample.json file to current folder

  -r, --results         Autosave results to specified file

  --help                Display this help screen.

  --version             Display version information.

sqlstresscmd 0.9.14.0
Copyright ©  2006, 2007 Adam Machanic
Check for updates at: https://github.com/ErikEJ/SqlQueryStress
Sample usage:
sqlstresscmd -s saved.json -t 32

  -s, --settingsFile    File name of saved session settings

  -d, --dbserver        Database Server

  -t, --threads         Number of threads, default 1

  -i, --input           Path to .sql script to execute

  -x, --xtract          Extract sample.json file to current folder

  -r, --results         Autosave results to specified file

  --help                Display this help screen.

  --version             Display version information.



C:\repo\SqlQueryStress\src\publish>
```
It seems that the cmd version prints help text twice. Am I missed anything? Thanks.

**Comment by ErikEJ** [comment]
Why do you need net6-windows?

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
Frankly speaking, I'm not very familiar with dot net core. The first time I run the build command without modifying `TargetFrameworks`, I got an error. I googled around and found that it's the added `--framework net6.0-windows` generated the error. But when I remove it, I got another error. So that's why I added `net6.0-windows` to the `TargetFrameworks` of the cmd version app.

**Comment by ErikEJ** [comment]
Maybe you have the 
Net tool install and run both - it looks like the tool is called twice

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
> Maybe you have the Net tool install and run both - it looks like the tool is called twice

What do you mean by the "Net tool"? I used Microsoft sysinternals tool procmon to monitor the process `sqlstresscmd.exe`, and I only found one `Process Start` and one `Process Exit` (still with the help info printed twice). So it's not possible that it was called twice. When you run the command with `--help`, did you get the help info twice?

**Comment by ErikEJ** [comment]
I am not at my computer for a couple of days, will check then. Could be a bug in the implementation of the help flow, yes.
