### ISSUE TITLE
How to calculate "Actual Second/Iteration (Avg)" and explaining a large difference for it given about the same input

### ISSUE THREAD

**Issue by buckleyGI** [ErikEJ/SqlQueryStress#147]
Trying to make sense of the number that is labeled **"Actual Second/Iteration (Avg)"**

My guess is that it is    (1) / (2) = (3) as in the first screenshot?

If I do the calculation I get for the 2 screenshots I get

```
(14*60+55)/50
= 17,9    <> 28,8502

(14*60+40)/50
= 17,6    <> 18,8402
```

Can you please comment on
1. How should I perform the calculation to get the "Actual Second/Iteration (Avg)". Are all the numbers on the screenshot there to derive it?
2. As you can see the tool has a total different value for "Actual Second/Iteration (Avg)", **even though the input is about the same** :  28,8502 vs 18,8402
Even though I don't currently know how to calculate it, it is a mystery to me why the "Actual Second/Iteration (Avg)" differs so much given the other data is about the same.

I'm trying to make sense of this large difference and connect them with
1. The results of the 2nd screenshot was obtained after the 1st screenshot.
Maybe there is a bug where the tool remembers state? I don't think I need to close the tool on each trial though right?
3. For the 2nd screenshot, I set the sql server compatibility level of the database from 2008 to 2019 ([I'm doing the stackoverflow benchmark as describe on the blog of Brent Ozar](https://www.brentozar.com/archive/2015/05/how-to-fake-load-tests-with-sqlquerystress/)). 
Doing this could make the performance better but I still can't calculate that "Actual Second/Iteration (Avg)" given the other numbers on the screenshot.

**Screenshot 1**
![image](https://github.com/ErikEJ/SqlQueryStress/assets/2102864/d463975a-ebdb-40dd-b723-d0fd12602ac4)
**Screenshot 2 (changed the compatibility level)**
![image](https://github.com/ErikEJ/SqlQueryStress/assets/2102864/3f5c9813-215d-4b26-8b09-e7c70064ac66)

**Comment by buckleyGI** [comment]
I also set the setting to true so that all the results are streamed to the client in the 2nd screenshot.
Although I think that isn't relevant give that all the numbers are about the same.

**Comment by ErikEJ** [comment]
This is part if the original implementation, and not something I have touched the last 15 years. Maybe there is some info in the wiki?

**Comment by ErikEJ** [comment]
Any updates?

**Comment by buckleyGI** [comment]
Ideally the metrics displayed are accompanied by an explanation.
I favor a question mark that shows what it conveys when you have over it. This will be some work that I currently don't have the cycles for.
AFAIK there is no documentation that is reachable from the GUI. That would be a place for it as well.

**Comment by DannyRichardsonWG** [comment]
I'm not sure but It looks like GetInfoMessages is firing multiple times for the same connection/query so the elapsed/cpu times are counted more than once (so two messages with 2000 in one and 3000 in the later one = 5000 for that single query). You should be able to replicate by putting a breakpoint on the parsing code and running a test with 1 iteration and 1 thread

Proposed fix:

Track times by connection client ID in a dictionary so the value is only counted once. Then after each query completes allocate that to a global counter.

GetInfoMessages

`         //we have times
                    if (matches.Length > 1)
                    {
                        var conn = (SqlConnection)sender;
                        var id = conn.ClientConnectionId;

                        //could probably add this to the connection creation area to tidy it up
                        if (!_outInfo.CpuTimes.TryGetValue(id, out var _))
                        {
                            _outInfo.CpuTimes.Add(conn.ClientConnectionId, 0);
                            _outInfo.ElapsedTimes.Add(conn.ClientConnectionId, 0);
                        }
                        //set the values for this connection to the last known amount
                        _outInfo.CpuTimes[id] = Convert.ToDouble(matches[1], CultureInfo.InvariantCulture);
                        _outInfo.ElapsedTimes[id] = Convert.ToDouble(matches[2], CultureInfo.InvariantCulture);

                        //_outInfo.CpuTime += Convert.ToInt32(matches[1], CultureInfo.InvariantCulture);
                        //_outInfo.ElapsedTime += Convert.ToInt32(matches[2], CultureInfo.InvariantCulture);
                    }`

And then QueryOutput updates

`  public class QueryOutput
        {
            public double CpuTime => trackedCpu + CpuTimes.Values.Sum();
            public Exception E;
            public double ElapsedTime => trackedElapsedTime + ElapsedTimes.Values.Sum();
            public bool Finished;
            public int LogicalReads;
            public TimeSpan Time;

            public ConcurrentDictionary<Guid, double> CpuTimes = new();
            public ConcurrentDictionary<Guid, double> ElapsedTimes = new();

            private double trackedCpu = 0;
            private double trackedElapsedTime = 0;
            private object updateLock = new();


            public void ClearTimes(Guid clientId)
            {
                lock (updateLock)
                {
                    if (CpuTimes.TryGetValue(clientId, out double cpu))
                        CpuTimes[clientId] = 0;
                    if (ElapsedTimes.TryGetValue(clientId, out double elapsed))
                        ElapsedTimes[clientId] = 0;

                    trackedCpu += cpu;
                    trackedElapsedTime += elapsed;
                }
            }
...
`

With these changes my results look more consistent. 

I only saw the tool today so I'm not very familiar with it so if that explanation makes sense to you and you can duplicate the multi-message I'm happy to put a PR in with the changes next week when I get some time to tidy it up.

**Comment by ErikEJ** [comment]
@DannyRichardsonWG Feel free to creat a PR!

**Comment by ErikEJ** [comment]
@DannyRichardsonWG Any plans to submit a PR?

**Comment by ErikEJ** [comment]
@DannyRichardsonWG I am not able to reproduce the duplicate message events
