### ISSUE TITLE
Compiled version for download

### ISSUE THREAD

**Issue by BrentOzar** [ErikEJ/SqlQueryStress#15]
Howdy! I teach training classes with SqlQueryStress, and students have said they'd love to use this newer version (I still use Adam's old one), but they don't have Visual Studio to compile the code. The next time you do a release, can you include the exe? Thanks!

**Comment by michael-rutherford** [comment]
I'm not in a position to link you to an updated exe, but FYI, Visual studio community 2015 is available for free.
https://www.visualstudio.com/en-us/products/visual-studio-community-vs.aspx

**Comment by BrentOzar** [comment]
@michael-rutherford yeah, so is Linux, but I can't go recommending people go learn to use this stuff just in order to run a 60KB program. :-D

**Comment by michael-rutherford** [comment]
@BrentOzar "but they don't have Visual Studio to compile the code" completely warranted my response. Take it or leave it. You're welcome.

**Comment by ErikEJ** [comment]
@BrentOzar Hi Brent, a download link to the a zip file with latest version is now available from the readme page https://github.com/ErikEJ/SqlQueryStress

**Comment by BrentOzar** [comment]
Woohoo, that's perfect! Updated my blog post to point to it. Thanks, and have a good weekend!
