### ISSUE TITLE
Errors with settings files

### ISSUE THREAD

**Issue by erikdarlingdata** [ErikEJ/SqlQueryStress#159]
Here's the version I'm on:

<img width="144" alt="image" src="https://github.com/user-attachments/assets/95da7ed0-5b4c-4954-8b3b-71dc680d8ced">

When I try to save a settings file, I get this error:

<img width="386" alt="image" src="https://github.com/user-attachments/assets/87520dd7-f46a-4095-a5ad-c9a1a1e03752">

When I try to re-use an older settings file, I get this error:

<img width="222" alt="image" src="https://github.com/user-attachments/assets/a2cb3a21-4f08-4ba7-b08a-839d0ba07e5c">

Thanks!

**Comment by ErikEJ** [comment]
@erikdarlingdata Thanks for reporting this.

I believe this (at least the first part) was fixed some time ago - version .166 is the latest:

https://github.com/ErikEJ/SqlQueryStress/releases

**Comment by erikdarlingdata** [comment]
@ErikEJ thanks, i'll give that a shot in a few!

**Comment by erikdarlingdata** [comment]
@ErikEJ yep, all good on that build. thanks again!
