### ISSUE TITLE
can't connect

### ISSUE THREAD

**Issue by mikeblas** [ErikEJ/SqlQueryStress#161]
When I try to connect this app to my database, I get a message box with the content "can't connect" and an empty title bar. This happens if I use SQL Server authentication or Integrated Authentication. 

The message doesn't give me any diagnostic information at all.

![image](https://github.com/user-attachments/assets/8edcccb6-40f5-4e5f-bd7b-d21ce46b2404)

**Comment by mikeblas** [comment]
Looks like `TrustServerCertificate=True` must be added to the "additional parameters" box to trust the server certificate (since I don't have cert issued from a trustworthy source). It would be handy if an option was added for this.

**Comment by ErikEJ** [comment]
What Server version are you connecting to?

**Comment by ErikEJ** [comment]
@mikeblas Ping?

**Comment by mikeblas** [comment]
```
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Microsoft SQL Server 2022 (RTM-CU14-GDR) (KB5042578) - 16.0.4140.3 (X64) 
	Aug 13 2024 13:46:25 
	Copyright (C) 2022 Microsoft Corporation
	Developer Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: )

```

**Comment by ErikEJ** [comment]
@mikeblas have you tried with encryption option: Strict ?

**Comment by mikeblas** [comment]
Yes. With "Strict", I get the same "connection failed" error message with the blank title bar.
