### ISSUE TITLE
No textbox to type a query

### ISSUE THREAD

**Issue by bigleka** [ErikEJ/SqlQueryStress#17]
Hi, I just donwload and compile, the main screen don´t show the left textbox do type a T-SQL.
and if I try run whitout nothing a exception appear: "ExecuteNonQuery: CommandText property not initialized"

**Comment by ErikEJ** [comment]
Could you try with the latest release version, and see if you have the same issue?

**Comment by bigleka** [comment]
Hi, I download the last commit f57ec4d

**Comment by ErikEJ** [comment]
Could you try out the latest zip from the link in read me.md ?

**Comment by bigleka** [comment]
Same situation
![sqlstress](https://cloud.githubusercontent.com/assets/13354954/14495484/063aa35e-0166-11e6-8d46-d24a140405c7.png)

**Comment by ErikEJ** [comment]
Interesting - what OS language do you have?

**Comment by bigleka** [comment]
I´m using a Windows 7 in Brazilian Portuguese

**Comment by ErikEJ** [comment]
Have updated the source, could you check if  that fixes your issue - thanks for reporting this!

**Comment by bigleka** [comment]
works fine.
tnks.
