### ISSUE TITLE
Update help-about

### ISSUE THREAD

**Issue by BrentOzar** [ErikEJ/SqlQueryStress#19]
Currently points to Adam's old DataManipulation.net (which is gone), and has the old version numbers.

(I feel bad logging an issue this small, but hey, it's pretty clear, hahaha, and you deserve the credit for the current version.)

**Comment by ErikEJ** [comment]
No issue is "too small" - this has been fixed!

**Comment by BrentOzar** [comment]
Hahaha, thanks sir!
