### ISSUE TITLE
New feature request: time delay between queries

### ISSUE THREAD

**Issue by BrentOzar** [ErikEJ/SqlQueryStress#21]
Sometimes I like to display the effect of concurrency on queries - if people are jumping in and out getting their own locks and leaving, then they're fine. But as more simultaneous queries pile up, blocking problems can pop up.

It'd be sweet to have a "Delay Between Queries, MS" edit box that lets you specify a delay in milliseconds between running queries on each thread. (I say milliseconds because I can see using this with ranges between 0ms and 5,000ms.)

**Comment by ErikEJ** [comment]
Fixed!
