### ISSUE TITLE
SQLQueryStress just supports english locale

### ISSUE THREAD

**Issue by fmms** [ErikEJ/SqlQueryStress#29]
Hi,

I have tested SQLQueryStress with an SQL Server where my default language ist German.
Doing so the "CPU Seconds/Iteration (Avg)" and "Logical Reads/Iteration (Avg)" and "Actual Seconds/Iteration (Avg)" did not show up.

After changing my language to english it worked.

I guess this is caused by https://github.com/ErikEJ/SqlQueryStress/blob/8e0bf22245df54e58e1a33aa1175e34afebec843/src/SQLQueryStress/LoadEngine.cs#L330 

Thanks for the tool!

Felix

**Comment by ErikEJ** [comment]
This is fixed in the latest build, pls let me know if it works for you
