### ISSUE TITLE
Fill ApplicationName with something distinguishable

### ISSUE THREAD

**Issue by fmms** [ErikEJ/SqlQueryStress#30]
Hi,

when looking at a profilter trace, SqlQueryStress ist hard to filter as it does not overwrite the default .NET ApplicationName: `.Net SqlClient Data Provider `

See https://social.msdn.microsoft.com/Forums/en-US/89437a55-e237-4a7e-9925-2ab3c795c989/net-sqlclient-data-provider-how-to-change-this-value-to-specific-name-of-application-in?forum=adodotnetdataproviders

I would prefer this to be `SqlQueryStress`.

regards
Felix

**Comment by ErikEJ** [comment]
Great suggestion? Is this something you could submit a pull request for?
