### ISSUE TITLE
Several Instances of SqlQueryStress should have different window titles

### ISSUE THREAD

**Issue by fmms** [ErikEJ/SqlQueryStress#31]
Hi,

I have several instances of SqlQueryStress opened. They are hard to find again as they all have the same window title ...

When opening from a file it woul be great to show the file name in the window title, otherwise numbering should be helpfull. e.g. `Session1 - SqlQueryStress`. Compare Word and Excel for example.

Felix

**Comment by ErikEJ** [comment]
I can add the filename, but unlike Word and Excel several instances of SQLQueryStress are individual processes, that have no knowledge of each other.

**Comment by ErikEJ** [comment]
There is no option to open a .sql file, only a settings file
