### ISSUE TITLE
Error after stopping and starting

### ISSUE THREAD

**Issue by kevriley** [ErikEJ/SqlQueryStress#36]
If you stop a run of SQLQueryStress by hitting 'Cancel', then restart it with 'Go', let the process finish, and then press 'Go' again, when the second run finishes you get the error

> Value of '101' is not valid for 'Value'. 'Value' should be between 'minimum' and 'maximum'.
> Parameter name: Value

![image](https://cloud.githubusercontent.com/assets/6805015/18585095/c847e8b4-7c0c-11e6-9a6f-18e3c7f7fff1.png)

Steps to reproduce
1. Type 'exec sp_configure' in the query window (any query will do really)
2. Set number of iterations = 100
3. Set number of threads = 10 (essentially set these 2 high enough so that the full run will take a few seconds and give you the chance to stop it part way through)
4. Click 'Go'
5. Cick 'Cancel'
6. Click 'Go' to allow the first run to complete
7. Click 'Go' to do a second run
8. Error
9. Click 'Continue' leaves the app in hung state and I have to kill from Task Manager

![image](https://cloud.githubusercontent.com/assets/6805015/18585093/c4751d42-7c0c-11e6-8dad-aad977be1136.png)

Full text of the error (with loaded assemblies removed for clarity):

> Value of '101' is not valid for 'Value'. 'Value' should be between 'minimum' and 'maximum'.
> Parameter name: Value
> See the end of this message for details on invoking 
> just-in-time (JIT) debugging instead of this dialog box.
> 
> *************\* Exception Text **************
> System.ArgumentOutOfRangeException: Value of '101' is not valid for 'Value'. 'Value' should be between 'minimum' and 'maximum'.
> Parameter name: Value
>    at System.Windows.Forms.ProgressBar.set_Value(Int32 value)
>    at SQLQueryStress.Form1.UpdateUi()
>    at SQLQueryStress.Form1.backgroundWorker1_RunWorkerCompleted(Object sender, RunWorkerCompletedEventArgs e)
>    at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)

**Comment by ErikEJ** [comment]
This should be fixed in the latest build, pls let me know if it works for you
