### ISSUE TITLE
Moar threads

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/SqlQueryStress#4]
Enable more than 200 simultaneous threads. This was just an arbitrary number and can be changed by simply modifying the appropriate control. But perhaps there is a smarter way to come up with a maximum?

**Comment by gotqn** [comment]
What's the current maximum? 200 sounds like to small number for me.  For example, if I want to test 5 or 10 k simultaneous request and see how the sql server is reacting.

**Comment by ErikEJ** [comment]
Wonder if you can do that on a single Windows machine?

**Comment by gotqn** [comment]
You mean the solution is to install the tool on different machines and somehow to start them at the same time?

**Comment by gotqn** [comment]
If I want to simulate, let's say, the activity of 5 000 users and the same time, having 200 connections per one tool, means I need 25 different machines - as I know it is a good practice to install the tool not on the machine running the SQL Server, so I guess it is not good to open the tool several times on one machine? 

Let's say I have the machines and the tool ready to be started. It will take me 5 minutes (more or less) to open each machine and start the test - which mean I am not able to simulate how the instance is going to handle such number of simultaneous requests (as they are not simultaneous) , right?

**Comment by SGK1977** [comment]
I have been running about 6 instances of this tool in about 4 machines to generate close to 4400 concurrent users. But beyond 6 instances the tool does not respond well. Are there any tweaks to make it handle more number of requests from each machine?

**Comment by ErikEJ** [comment]
@SGK1977 What does "not respond well" mean? Maybe the server is too busy?

**Comment by MisterZeus** [comment]
More threads might also lead to out-of-memory exceptions, if you set them too high:
https://eknowledger.wordpress.com/2012/05/01/max-number-of-threads-per-windows-process/

**Comment by ErikEJ** [comment]
Command line options are now supported, so you can run multiple instances of the tool, each with many threads:
https://github.com/ErikEJ/SqlQueryStress/blob/master/src/SQLQueryStress/CommandLineOptions.cs
