### ISSUE TITLE
Add ability to speficy additional connection parameters

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/SqlQueryStress#45]

**Comment by stifing** [comment]
Hi 

Is it possible to include : ; MultiSubnetFailover=True /False connection parameter as well ?

**Comment by ErikEJ** [comment]
You dont need it: https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql/sqlclient-support-for-high-availability-disaster-recovery

**Comment by ErikEJ** [comment]
Actually looking like you need it with .NET Core.

**Comment by ccpDeNormalized** [comment]
Hi Erik - i'd love to see the db encryption params included - Encrypt=True and TrustServerCertificate=True

**Comment by ErikEJ** [comment]
@ccpDeNormalized is the absence of these blocking you?

**Comment by ErikEJ** [comment]
@ccpDeNormalized Ping?
