### ISSUE TITLE
What about print, raiserror statements?

### ISSUE THREAD

**Issue by Oleg26Dev** [ErikEJ/SqlQueryStress#47]
Is it possible to output info of these statements as SSMS does it?

**Comment by ErikEJ** [comment]
Sure, anything is possible - do you have a design proposal?

**Comment by Oleg26Dev** [comment]
Probably as in SSMS: split the main window and put output to the low panel

**Comment by BrentOzar** [comment]
@Oleg26Dev but what would you want to have done as hundreds of these queries run? How are you going to tie which messages show up from which executions, for example, or queries that dump dozens/hundreds of lines into the messages?

**Comment by ErikEJ** [comment]
This is not something I plan to add
