### ISSUE TITLE
Temporal Table IO Reads not being reflected

### ISSUE THREAD

**Issue by jthalliens** [ErikEJ/SqlQueryStress#48]
[LoadEngine.zip](https://github.com/ErikEJ/SqlQueryStress/files/985351/LoadEngine.zip)

Hi There,

I've been using this tool for some time and I noticed that when a #temp table is created within a SP or SQL Query the IO reads generated by these objects are not being counted by the application due to the fact that the regex it has to collect that kind of information only works for normal tables but not for #temp table. Steps to reproduce:

Create a SP or SQL query which contains a #Temp table and you'll notice that the read generated are not counted by the app. 

I used the http://www.statisticsparser.com/ to compare against. I have a fix for this but not sure what's the process to check in the code, minor changes. Please take a look at the changes at https://github.com/jthalliens/src/blob/master/SQLQueryStress/LoadEngine.cs line 385 & 334

**Comment by ErikEJ** [comment]
Thanks, you can do a pull request, or just share your changes here, and I will get them in the product!

**Comment by jthalliens** [comment]
Hi Erik,

I had some issues trying to do the pull request, file attached with the changes, please let me know when I can get the latest.

Thanks

**Comment by ErikEJ** [comment]
I am not very good at regex, can you explain this line:

     _outInfo.LogicalReads += Convert.ToInt32(matches[2]);

(was _outInfo.LogicalReads += Convert.ToInt32(matches[1]); before)

**Comment by jthalliens** [comment]
Sure,
Once the modification to the regex was applied in order to get information for #temp tables and ##global temp tables a new position was automatically created on the matches vector, meaning that in order to get the value for IO reads I had to increase the index at 2. in general were minor changes

**Comment by ErikEJ** [comment]
But what about the value in matches[1] ???

**Comment by jthalliens** [comment]
the matches[1] was working prior to the implementation but after the changes a new position was created that's why I had to use 2 over the IO reads assignment, you can debug the code and see the new position created if I continue using [1] an exception will be thrown

**Comment by ErikEJ** [comment]
Is that also the case fro "plain" SQL with no temp tables?

**Comment by jthalliens** [comment]
That's correct it's working for those scenarios too.
