### ISSUE TITLE
Save statistics

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/SqlQueryStress#5]
Implement support for saving of statistics and collected information, and reporting on that data, especially when the same test is run more than once

**Comment by CliftonHS** [comment]
Is this already done?
Collected information may need more clarification (the issue being old notwithstanding)

Currently reports cover average  CPU, elapsed time, logical reads, among others. 

I could see adding new counters that do not necessarily have to be shown in the form like physical reads, rows effected (_to explain random parameter results_), memory grants, etc

Thoughts?

**Comment by ErikEJ** [comment]
I guess one could consider it already done. It is an very old issue..
