### ISSUE TITLE
Save settings (delay between queries)

### ISSUE THREAD

**Issue by jmf70** [ErikEJ/SqlQueryStress#54]
Hi,
the **Save Settings** option doesn't save **Delay Between Queries** value or Load Settings option doesn't recover it.
This happens in last version as well.

Thank you

**Comment by ErikEJ** [comment]
Is that really part of "Settings/Options" ?

**Comment by jmf70** [comment]
Hi,
yes I think so, why not?
I think the options **Number of Iterations**, **Number of Threads** & **Delay Between Queries** belongs to the same options group and this is the only one which doesn't saves.

THX.

**Comment by ErikEJ** [comment]
Fixed in latest build, please let me know if it works for you!

**Comment by jmf70** [comment]
Hi,
It runs perfect.
Thank you very much.
