### ISSUE TITLE
File-save doesn't include the delay

### ISSUE THREAD

**Issue by BrentOzar** [ErikEJ/SqlQueryStress#56]
Howdy sir! Small bug - set up a load test with a delay between queries specified (say 100ms), then click File, Save Settings. Close SQLQueryStress, and load the settings file - the delay is back to 0.

**Comment by ErikEJ** [comment]
On latest build?

**Comment by BrentOzar** [comment]
My apologies! I could have sworn I was on the latest build, but no. Doesn't happen on 0.9.7.53. Closing. Sorry about that!

**Comment by ErikEJ** [comment]
No worries, it was fixed like 2 days ago. You could "watch" this repo to keep up to date (will not incur too much extra mail, quiet here)

**Comment by ErikEJ** [comment]
I have logged #57

**Comment by BrentOzar** [comment]
Oh yeah, I've totally been watching the repo, I just...must have missed this one. (sigh) Too many emails. Sorry about that!
