### ISSUE TITLE
Multiple test queries

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/SqlQueryStress#6]
Implement support for multiple test queries

**Comment by rayzorben** [comment]
I second this!

**Comment by ErikEJ** [comment]
How do you envision that to be designed? (you can write multiple statements already)

**Comment by CliftonHS** [comment]
Perhaps @ErikEJ , this issue was completed and needed to be closed?

**Comment by ErikEJ** [comment]
@CliftonHS you may be right, please explain ☺️

**Comment by CliftonHS** [comment]
It depends if the the idea was _multiple_ queries or _simultaneous_ queries. You are right, the GUI runs multiple queries but all in the same batch. But this is already baked in SqlCommand, no coding changes are required unless we wanted different transactions.

> **Extra Credit**
> Now, to have simultaneous runs, the method is to stage different JSON config files and run them. However, would this not require manual effort? I did not see how I could add an argument to point to my config file, which is a shame. And for what its worth, I had not yet decided if this would be something I could contribute yet.
> 
> `.\SQLQueryStress.exe "path-to-config"`
> 
> To me, an existence of running the program via command line would take the program to that missing next level in development, since I could make the entire tool dynamic in my unit and regressive tests.
> - like testing the performance of a given SELECT statement during maintenance operations (system or instance!), data lake uploads, scaling of UPSERTs on overall performance, other highly visible workflows, or testing race conditions, impact on critical workflows.

**Comment by ErikEJ** [comment]
Command line options are supported, so closing this.

https://github.com/ErikEJ/SqlQueryStress/blob/master/src/SQLQueryStress/CommandLineOptions.cs
