### ISSUE TITLE
AppVeyor latest build not working

### ISSUE THREAD

**Issue by BrentOzar** [ErikEJ/SqlQueryStress#67]
The home page of the project has this link as the latest build from AppVeyor:

https://ci.appveyor.com/api/projects/ErikEJ/SqlQueryStress/artifacts/SqlQueryStress.zip?branch=master

But it's 404'ing.

**Comment by ErikEJ** [comment]
AppVeyour only store artifacts for 6 months now, and the latest build was nine months old 😲  - up again now

**Comment by BrentOzar** [comment]
Awesome, thanks sir!
