### ISSUE TITLE
Unable to build the project.

### ISSUE THREAD

**Issue by nhudacin** [ErikEJ/SqlQueryStress#7]
I'm using Visual Studio 2015 Enterprise edition... 

Process to Recreate: 
1. Forked the repo
2. Did a git clone to my workstation
3. Opened the solution in Visual Studio 2015
4. Right-Clicked the project "SQLQueryStress" and chose "Build"

This error occurs in the DEBUG configuration (not the RELEASE configuration)

Errors Received: 
Severity	Code	Description	Project	File	Line
Error	CS7036	There is no argument given that corresponds to the required formal parameter 'value' of 'Dictionary<string, int>.Add(string, int)'	SQLQueryStress	C:\_SourceControl\NHGIT\SqlQueryStress\src\SQLQueryStress\Form1.cs	197
Error		Unable to find manifest signing certificate in the certificate store.	SQLQueryStress		

Screen shot: 
![image](https://cloud.githubusercontent.com/assets/6682884/12122109/c2c55f48-b39e-11e5-8a64-c30a70dbc95b.png)

Also received 1 warning: 
Severity	Code	Description	Project	File	Line
Warning		Unable to find code signing certificate in the current user’s Windows certificate store. To correct this, either disable signing of the ClickOnce manifest or install the certificate into the certificate store.	SQLQueryStress		

Screen shot: 
![image](https://cloud.githubusercontent.com/assets/6682884/12122151/ec783ffe-b39e-11e5-9edb-d6c59f36943d.png)

Building the solution doesn't work either.

**Comment by ErikEJ** [comment]
Fixed
