### ISSUE TITLE
Cancel button does not work

### ISSUE THREAD

**Issue by sharpboy2008** [ErikEJ/SqlQueryStress#71]
after clicking cancel button ,it 's not working and it always put UI in readonly mode.

**Comment by BrentOzar** [comment]
Just to echo this - sometimes, when you click Cancel, the queries finish, but SQLQueryStress thinks they're still running. For me, the fix has been to go into Task Manager and force-quit SQLQueryStress.

**Comment by ErikEJ** [comment]
I will try to investigate.

**Comment by ErikEJ** [comment]
I attempted a fix in the latest daily build
