### ISSUE TITLE
Setting more than 2 threads does not work and no error message

### ISSUE THREAD

**Issue by tgspacelabs** [ErikEJ/SqlQueryStress#76]
Running the SQLQueryStress.exe

I set my query to SELECT @@VERSION; and set the threads to 2.  It works fine.  I then update the threads to 5 as shown and the program fails to execute but gives no error message or indication that it failed.

Good:
![image](https://user-images.githubusercontent.com/24533761/62056268-25fb8580-b1d2-11e9-822f-21fb930be29d.png)

Bad:
![image](https://user-images.githubusercontent.com/24533761/62056119-d7e68200-b1d1-11e9-9982-3528ea1bba2d.png)

**Comment by tgspacelabs** [comment]
I've traced the problem to the MinPool Size and Max Pool Size connection string parameters:
Development machine:
...Pooling=True;Min Pool Size=5;**Max Pool Size=5**;...

Test Machine:
...Pooling=True;Min Pool Size=5;**Max Pool Size=2**;...

**Comment by ErikEJ** [comment]
So we can close this?

**Comment by tgspacelabs** [comment]
No, the Max Pool Size should always be equal to or greater than Min Pool Size and clearly it is not.

**Comment by tgspacelabs** [comment]
No, the Max Pool Size should always be equal to or greater than Min Pool Size and clearly it is not.

**Comment by tgspacelabs** [comment]
No, the Max Pool Size should always be equal to or greater than Min Pool Size and clearly it is not.

**Comment by ErikEJ** [comment]
Fixed in latest build, thanks for reporting this
