### ISSUE TITLE
Profiler Events on Azure?

### ISSUE THREAD

**Issue by MarkMcPartland** [ErikEJ/SqlQueryStress#77]
Not sure if this is an issue or other.
When running on an AZURE SQL DB, see no events at all for the query runs in the SQL Server profiler (Azure Data Studio)
Of course, when running on local SQL DB, events are seen as expected in its Profiler

App issue?

**Comment by ErikEJ** [comment]
Not sue how this question relates to this app?

But you cannot run profiler against Azure SQL DB: https://serverfault.com/questions/935289/connect-sql-server-profiler-2017-to-azure-sql-server

**Comment by MarkMcPartland** [comment]
Didn't expect it to be an app thing but had to ask the question.
Understand you cant run the usual profiler with Azure SQL, but you there is an Azure SQL profiler, run through Azure Data Studio: 
https://docs.microsoft.com/en-us/sql/azure-data-studio/sql-server-profiler-extension?view=sql-server-ver15
So it is here that interestingly no events are seen.
cheers

**Comment by ErikEJ** [comment]
Maybe you should report a bug here: https://github.com/microsoft/azuredatastudio ?
