### ISSUE TITLE
AppVeyor link down

### ISSUE THREAD

**Issue by BrentOzar** [ErikEJ/SqlQueryStress#78]
Howdy sir! Looks like on the home page of the repo:

https://github.com/ErikEJ/SqlQueryStress

The AppVeyor link is down:

https://ci.appveyor.com/api/projects/ErikEJ/SqlQueryStress/artifacts/SqlQueryStress.zip?branch=master

Gives an error saying: "The specified blob does not exist. RequestId:93a2de2f-e01e-0086-666f-fbc1df000000 Time:2020-03-16T08:46:03.9279219Z"

**Comment by ErikEJ** [comment]
That time of the year! Fixed.

**Comment by BrentOzar** [comment]
Thanks sir!
