### ISSUE TITLE
Mark load threads as IsBackground = true

### ISSUE THREAD

**Issue by moserware** [ErikEJ/SqlQueryStress#85]
Load threads [are currently being created](https://github.com/ErikEJ/SqlQueryStress/blob/ae7231c86c1161857a9c041be4fd7b68beff31a3/src/SQLQueryStress/LoadEngine.cs#L150) as:

```
var theThread = new Thread(input.StartLoadThread) {Priority = ThreadPriority.BelowNormal};
```

You might consider setting `IsBackground = true` as well per [the docs](https://docs.microsoft.com/en-us/dotnet/api/system.threading.thread.isbackground):

>A thread is either a background thread or a foreground thread. Background threads are identical to foreground threads, except that background threads do not prevent a process from terminating. Once all foreground threads belonging to a process have terminated, the common language runtime ends the process. Any remaining background threads are stopped and do not complete.

This could explain why sometimes the threads keep running even after the application window exits.

**Comment by ErikEJ** [comment]
Sounds right - happy to get a Pull Request 😊

**Comment by ErikEJ** [comment]
I attempted a fix in the latest daily build
